const students = [
  "Pooja Agarwal",
  "Nathan Alexander",
  "Phillip Anthony",
  "Brittany Baker",
  "Michelle Beaudoin",
  "Bryan Buechler",
  "Erik Buss",
  "Kevin Cain",
  "Machiko Carroll",
  "Patrick Childers",
  "Tyler Collins",
  "Jonathan Cornet",
  "Matthew Dacanay",
  "Joe Dixon",
  "Devon Durst",
  "Daniel Escobedo",
  "Esther Franco",
  "Jonathan Garrett",
  "Bryan Gholipour",
  "Dian Gigrich",
  "Ryan Graham",
  "Jordan Johnson",
  "Artem Khomenko",
  "Kristen Killingsworth",
  "Victor Korn",
  "David Kovalchuk",
  "Rachel Lally",
  "Eileen Lu",
  "Tiffany Marko",
  "Tiarnan Marsten",
  "Andrew Massey",
  "Crayson Mcbride",
  "Bryce Mckenzie",
  "Shreya Mishra",
  "Dat Nguyen",
  "James Pace",
  "Arianna Reilly-Bush",
  "Mo Risk",
  "Heaton Schreiber",
  "Noah Schwartz",
  "Jaeger Snyder",
  "Hyerin Song",
  "Alex Thiel",
  "Darryl Tillman",
  "Jacob Tillman",
  "Jonathan Vu",
  "Sharrod Willanova",
  "Felisha Yu-macias",
  "Sangmi Yun",
  "Liyuan Zhao",
];
const first = students.map((stu) => stu.split(" ")[0]);
const last = students.map((stu) => stu.split(" ")[1]);

console.log(first);
console.log("==================");
console.log(last);
const firstnames = [
  "Pooja",
  "Nathan",
  "Phillip",
  "Brittany",
  "Michelle",
  "Bryan",
  "Erik",
  "Kevin",
  "Machiko",
  "Patrick",
  "Tyler",
  "Jonathan",
  "Matthew",
  "Joe",
  "Devon",
  "Daniel",
  "Esther",
  "Jonathan",
  "Bryan",
  "Dian",
  "Ryan",
  "Jordan",
  "Artem",
  "Kristen",
  "Victor",
  "David",
  "Rachel",
  "Eileen",
  "Tiffany",
  "Tiarnan",
  "Andrew",
  "Crayson",
  "Bryce",
  "Shreya",
  "Dat",
  "James",
  "Arianna",
  "Mo",
  "Heaton",
  "Noah",
  "Jaeger",
  "Hyerin",
  "Alex",
  "Darryl",
  "Jacob",
  "Jonathan",
  "Sharrod",
  "Felisha",
  "Sangmi",
  "Liyuan",
];
const lastnames = [
  "Agarwal",
  "Alexander",
  "Anthony",
  "Baker",
  "Beaudoin",
  "Buechler",
  "Buss",
  "Cain",
  "Carroll",
  "Childers",
  "Collins",
  "Cornet",
  "Dacanay",
  "Dixon",
  "Durst",
  "Escobedo",
  "Franco",
  "Garrett",
  "Gholipour",
  "Gigrich",
  "Graham",
  "Johnson",
  "Khomenko",
  "Killingsworth",
  "Korn",
  "Kovalchuk",
  "Lally",
  "Lu",
  "Marko",
  "Marsten",
  "Massey",
  "Mcbride",
  "Mckenzie",
  "Mishra",
  "Nguyen",
  "Pace",
  "Reilly-Bush",
  "Risk",
  "Schreiber",
  "Schwartz",
  "Snyder",
  "Song",
  "Thiel",
  "Tillman",
  "Tillman",
  "Vu",
  "Willanova",
  "Yu-macias",
  "Yun",
  "Zhao",
];
firstnames.forEach (stu=>console.log(stu))
const toSort = [
  "Pooja Agarwal",
  "Nathan Alexander",
  "Phillip Anthony",
  "Michelle Beaudoin",
  "Bryan Buechler",
  "Erik Buss",
  "Kevin Cain",
  "Machiko Carroll",
  "Jonathan Cornet",
  "Matthew Dacanay",
  "Joe Dixon",
  "Devon Durst",
  "Esther Franco",
  "Jonathan Garrett",
  "Bryan Gholipour",
  "Dian Gigrich",
  "Ryan Graham",
  "Jordan Johnson",
  "Artem Khomenko",
  "Kristen Killingsworth",
  "Victor Korn",
  "David Kovalchuk",
  "Rachel Lally",
  "Eileen Lu",
  "Tiffany Marko",
  "Tiarnan Marsten",
  "Andrew Massey",
  "Crayson Mcbride",
  "Bryce Mckenzie",
  "Shreya Mishra",
  "Dat Nguyen",
  "James Pace",
  "Mo Risk",
  "Heaton Schreiber",
  "Noah Schwartz",
  "Jaeger Snyder",
  "Hyerin Song",
  "Alex Thiel",
  "Darryl Tillman",
  "Jacob Tillman",
  "Jonathan Vu",
  "Sharrod Willanova",
  "Felisha Yu-macias",
  "Sangmi Yun",
  "Liyuan Zhao",
];
const sorted =  toSort.sort();
console.log(toSort)